### ISSUE TITLE
Narrator reads zero

### ISSUE THREAD

**Issue by bahri-dev** [jgillick/react-native-a11y-slider#3] opened 2023-03-30 16:41 UTC
In order to check accessibility of this Slider, I tried to open windows/narrator. Narrator always reads "zero percent". How can fix the issue?

**Comment by jgillick** [comment] 2023-04-13 00:16
Can you list the steps to reproduce? Was this on a physical device or an emulator? iOS or Android?

**Comment by jgillick** [comment] 2023-05-19 17:16
Closing this due to lack of steps to reproduce. Feel free to reopen, if necessary.

**Closed as completed by jgillick** 2023-05-19 17:16 UTC
